- name: Disable LLMNR
  hosts: all
  tasks:
    - name: Ensure LLMNR is disabled
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: LLMNR
        type: dword
        data: 0
        state: present
