---
- name: Configure Windows Machine
  hosts: windows
  tasks:
    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Git using Chocolatey
      win_chocolatey:
        name: git
        state: present

    - name: Create a directory on C drive
      win_file:
        path: C:\example-directory
        state: directory
